services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomm_db
    command: [ 'postgres', '-c', 'wal_level=logical' ]
    healthcheck:
      test: ['CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      ecomm_net:

  

networks:
  ecomm_net:
    name: ecomm_net
    driver: bridge
